# fly.toml app configuration file for whatsapp-sandc-feed
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whatsapp-sandc-feed'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/data'
  WEEKLY_SUMMARY_CRON = '0 19 * * 0'

[[mounts]]
  source = 'sandc_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
